export const SURAH_MEANINGS = {
    1: { tr: "Açılış", en: "The Opening", id: "Pembukaan", ar: "الفاتحة" },
    2: { tr: "İnek", en: "The Cow", id: "Sapi Betina", ar: "البقرة" },
    3: { tr: "İmran Ailesi", en: "The Family of Imran", id: "Keluarga Imran", ar: "آل عمران" },
    4: { tr: "Kadınlar", en: "The Women", id: "Wanita", ar: "النساء" },
    5: { tr: "Sofralar", en: "The Table Spread", id: "Hidangan", ar: "المائدة" },
    6: { tr: "En'am", en: "The Cattle", id: "Binatang Ternak", ar: "الأنعام" },
    7: { tr: "A'râf", en: "The Heights", id: "Tempat Tertinggi", ar: "الأعراف" },
    8: { tr: "Savaş Ganimetleri", en: "The Spoils of War", id: "Harta Rampasan Perang", ar: "الأنفال" },
    9: { tr: "Tövbe", en: "The Repentance", id: "Pengampunan", ar: "التوبة" },
    10: { tr: "Yunus", en: "Jonah", id: "Yunus", ar: "يونس" },
    11: { tr: "Hud", en: "Hud", id: "Hud", ar: "هود" },
    12: { tr: "Yusuf", en: "Joseph", id: "Yusuf", ar: "يوسف" },
    13: { tr: "Gök Gürültüsü", en: "The Thunder", id: "Guruh", ar: "الرعد" },
    14: { tr: "İbrahim", en: "Abraham", id: "Ibrahim", ar: "إبراهيم" },
    15: { tr: "Hicr", en: "The Rocky Tract", id: "Hijr", ar: "الحجر" },
    16: { tr: "Arı", en: "The Bee", id: "Lebah", ar: "النحل" },
    17: { tr: "İsra", en: "The Night Journey", id: "Perjalanan Malam", ar: "الإسراء" },
    18: { tr: "Kehf", en: "The Cave", id: "Gua", ar: "الكهف" },
    19: { tr: "Meryem", en: "Mary", id: "Maryam", ar: "مريم" },
    20: { tr: "Taha", en: "Ta-Ha", id: "Taha", ar: "طه" },
    21: { tr: "Enbiya", en: "The Prophets", id: "Para Nabi", ar: "الأنبياء" },
    22: { tr: "Hac", en: "The Pilgrimage", id: "Haji", ar: "الحج" },
    23: { tr: "Müminler", en: "The Believers", id: "Orang-orang Mukmin", ar: "المؤمنون" },
    24: { tr: "Nur", en: "The Light", id: "Cahaya", ar: "النور" },
    25: { tr: "Furkan", en: "The Criterion", id: "Pembeda", ar: "الفرقان" },
    26: { tr: "Şuara", en: "The Poets", id: "Para Penyair", ar: "الشعراء" },
    27: { tr: "Neml", en: "The Ant", id: "Semut", ar: "النمل" },
    28: { tr: "Kasas", en: "The Stories", id: "Cerita", ar: "القصص" },
    29: { tr: "Ankebut", en: "The Spider", id: "Laba-laba", ar: "العنكبوت" },
    30: { tr: "Rum", en: "The Romans", id: "Bangsa Romawi", ar: "الروم" },
    31: { tr: "Lokman", en: "Luqman", id: "Luqman", ar: "لقمان" },
    32: { tr: "Secde", en: "The Prostration", id: "Sajdah", ar: "السجدة" },
    33: { tr: "Ahzab", en: "The Combined Forces", id: "Golongan yang Bersekutu", ar: "الأحزاب" },
    34: { tr: "Sebe", en: "Sheba", id: "Kaum Saba", ar: "سبأ" },
    35: { tr: "Fatır", en: "Originator", id: "Pencipta", ar: "فاطر" },
    36: { tr: "Yasin", en: "Ya Sin", id: "Yasin", ar: "يس" },
    37: { tr: "Saffat", en: "Those Who Set The Ranks", id: "Barisan-barisan", ar: "الصافات" },
    38: { tr: "Sad", en: "The Letter \"Saad\"", id: "Sad", ar: "ص" },
    39: { tr: "Zümer", en: "The Troops", id: "Rombongan", ar: "الزمر" },
    40: { tr: "Mümin", en: "The Forgiver", id: "Orang yang Beriman", ar: "غافر" },
    41: { tr: "Fussilet", en: "Explained in Detail", id: "Yang Dijelaskan", ar: "فصلت" },
    42: { tr: "Şura", en: "The Consultation", id: "Musyawarah", ar: "الشورى" },
    43: { tr: "Zuhruf", en: "The Ornaments of Gold", id: "Perhiasan", ar: "الزخرف" },
    44: { tr: "Duhan", en: "The Smoke", id: "Kabut", ar: "الدخان" },
    45: { tr: "Casiye", en: "The Crouching", id: "Yang Berlutut", ar: "الجاثية" },
    46: { tr: "Ahkaf", en: "The Wind-Curved Sandhills", id: "Bukit-bukit Pasir", ar: "الأحقاف" },
    47: { tr: "Muhammed", en: "Muhammad", id: "Muhammad", ar: "محمد" },
    48: { tr: "Fetih", en: "The Victory", id: "Kemenangan", ar: "الفتح" },
    49: { tr: "Hucurat", en: "The Rooms", id: "Kamar-kamar", ar: "الحجرات" },
    50: { tr: "Kaf", en: "The Letter \"Qaf\"", id: "Qaf", ar: "ق" },
    51: { tr: "Zariyat", en: "The Winnowing Winds", id: "Angin yang Menerbangkan", ar: "الذاريات" },
    52: { tr: "Tur", en: "The Mount", id: "Bukit", ar: "الطور" },
    53: { tr: "Necm", en: "The Star", id: "Bintang", ar: "النجم" },
    54: { tr: "Kamer", en: "The Moon", id: "Bulan", ar: "القمر" },
    55: { tr: "Rahman", en: "The Beneficent", id: "Yang Maha Pemurah", ar: "الرحمن" },
    56: { tr: "Vakıa", en: "The Inevitable", id: "Hari Kiamat", ar: "الواقعة" },
    57: { tr: "Hadid", en: "The Iron", id: "Besi", ar: "الحديد" },
    58: { tr: "Mücadele", en: "The Pleading Woman", id: "Wanita yang Menggugat", ar: "المجادلة" },
    59: { tr: "Haşr", en: "The Exile", id: "Pengusiran", ar: "الحشر" },
    60: { tr: "Mümtehine", en: "She That Is To Be Examined", id: "Wanita yang Diuji", ar: "الممتحنة" },
    61: { tr: "Saff", en: "The Ranks", id: "Barisan", ar: "الصف" },
    62: { tr: "Cuma", en: "The Congregation, Friday", id: "Jumat", ar: "الجمعة" },
    63: { tr: "Münafikun", en: "The Hypocrites", id: "Orang-orang Munafik", ar: "المنافقون" },
    64: { tr: "Tegabun", en: "The Mutual Disillusion", id: "Hari Dinampakkan Kesalahan", ar: "التغابن" },
    65: { tr: "Talak", en: "The Divorce", id: "Talak", ar: "الطلاق" },
    66: { tr: "Tahrim", en: "The Prohibition", id: "Mengharamkan", ar: "التحريم" },
    67: { tr: "Mülk", en: "The Sovereignty", id: "Kerajaan", ar: "الملك" },
    68: { tr: "Kalem", en: "The Pen", id: "Pena", ar: "القلم" },
    69: { tr: "Hakka", en: "The Reality", id: "Hari Kiamat", ar: "الحاقة" },
    70: { tr: "Mearic", en: "The Ascending Stairways", id: "Tempat Naik", ar: "المعارج" },
    71: { tr: "Nuh", en: "Noah", id: "Nuh", ar: "نوح" },
    72: { tr: "Cin", en: "The Jinn", id: "Jin", ar: "الجن" },
    73: { tr: "Müzzemmil", en: "The Enshrouded One", id: "Orang yang Berselimut", ar: "المزمل" },
    74: { tr: "Müddessir", en: "The Cloaked One", id: "Orang yang Berkemul", ar: "المدثر" },
    75: { tr: "Kıyamet", en: "The Resurrection", id: "Hari Kiamat", ar: "القيامة" },
    76: { tr: "İnsan", en: "The Man", id: "Manusia", ar: "الإنسان" },
    77: { tr: "Mürselat", en: "The Emissaries", id: "Malaikat yang Diutus", ar: "المرسلات" },
    78: { tr: "Nebe", en: "The Tidings", id: "Berita Besar", ar: "النبأ" },
    79: { tr: "Naziat", en: "Those Who Drag Forth", id: "Malaikat yang Mencabut", ar: "النازعات" },
    80: { tr: "Abese", en: "He Frowned", id: "Ia Bermuka Masam", ar: "عبس" },
    81: { tr: "Tekvir", en: "The Overthrowing", id: "Menggulung", ar: "التكوير" },
    82: { tr: "İnfitar", en: "The Cleaving", id: "Terbelah", ar: "الانفطار" },
    83: { tr: "Mutaffifin", en: "The Defrauding", id: "Orang-orang yang Curang", ar: "المطففين" },
    84: { tr: "İnşikak", en: "The Sundering", id: "Terbelah", ar: "الانشقاق" },
    85: { tr: "Buruc", en: "The Mansions of the Stars", id: "Gugusan Bintang", ar: "البروج" },
    86: { tr: "Tarık", en: "The Morning Star", id: "Yang Datang di Malam Hari", ar: "الطارق" },
    87: { tr: "A'la", en: "The Most High", id: "Yang Paling Tinggi", ar: "الأعلى" },
    88: { tr: "Gasiye", en: "The Overwhelming", id: "Hari Pembalasan", ar: "الغاشية" },
    89: { tr: "Fecr", en: "The Dawn", id: "Fajar", ar: "الفجر" },
    90: { tr: "Beled", en: "The City", id: "Negeri", ar: "البلد" },
    91: { tr: "Şems", en: "The Sun", id: "Matahari", ar: "الشمس" },
    92: { tr: "Leyl", en: "The Night", id: "Malam", ar: "الليل" },
    93: { tr: "Duha", en: "The Morning Hours", id: "Waktu Dhuha", ar: "الضحى" },
    94: { tr: "İnşirah", en: "The Relief", id: "Melapangkan", ar: "الشرح" },
    95: { tr: "Tin", en: "The Fig", id: "Buah Tin", ar: "التين" },
    96: { tr: "Alak", en: "The Clot", id: "Segumpal Darah", ar: "العلق" },
    97: { tr: "Kadir", en: "The Power", id: "Kemuliaan", ar: "القدر" },
    98: { tr: "Beyyine", en: "The Clear Proof", id: "Bukti yang Nyata", ar: "البينة" },
    99: { tr: "Zilzal", en: "The Earthquake", id: "Kegoncangan", ar: "الزلزلة" },
    100: { tr: "Adiyat", en: "The Courser", id: "Kuda Perang", ar: "العاديات" },
    101: { tr: "Karia", en: "The Calamity", id: "Hari Kiamat", ar: "القارعة" },
    102: { tr: "Tekasür", en: "The Rivalry in World Increase", id: "Bermegah-megahan", ar: "التكاثر" },
    103: { tr: "Asr", en: "The Declining Day", id: "Masa", ar: "العصر" },
    104: { tr: "Hümeze", en: "The Traducer", id: "Pengumpat", ar: "الهمزة" },
    105: { tr: "Fil", en: "The Elephant", id: "Gajah", ar: "الفيل" },
    106: { tr: "Kureyş", en: "The Quraish", id: "Suku Quraisy", ar: "قريش" },
    107: { tr: "Maun", en: "The Small Kindnesses", id: "Barang-barang yang Berguna", ar: "الماعون" },
    108: { tr: "Kevser", en: "The Abundance", id: "Nikmat yang Berlimpah", ar: "الكوثر" },
    109: { tr: "Kafirun", en: "The Disbelievers", id: "Orang-orang Kafir", ar: "الكافرون" },
    110: { tr: "Nasr", en: "The Divine Support", id: "Pertolongan", ar: "النصر" },
    111: { tr: "Tebbet", en: "The Palm Fiber", id: "Lahab", ar: "المسد" },
    112: { tr: "İhlas", en: "The Sincerity", id: "Ikhlas", ar: "الإخلاص" },
    113: { tr: "Felak", en: "The Daybreak", id: "Waktu Subuh", ar: "الفلق" },
    114: { tr: "Nas", en: "Mankind", id: "Manusia", ar: "الناس" }
};

// SURAH_NAMES is now re-exported from the canonical source to maintain single source of truth
// This prevents inconsistencies between different files
export { SURAH_NAMES } from '../data/surahNames';

